// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using school_managment_system_backend.Models;

#nullable disable

namespace school_managment_system_backend.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("school_managment_system_backend.Models.Allocate_Classroom", b =>
                {
                    b.Property<int>("allocateClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("allocateClassRoomId"));

                    b.Property<string>("clsRoom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teachName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("allocateClassRoomId");

                    b.ToTable("Allocate_Classroom");
                });

            modelBuilder.Entity("school_managment_system_backend.Models.Allocate_Subjects", b =>
                {
                    b.Property<int>("allocatedSubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("allocatedSubId"));

                    b.Property<string>("subName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("allocatedSubId");

                    b.ToTable("Allocate_Subjects");
                });

            modelBuilder.Entity("school_managment_system_backend.Models.Classroom", b =>
                {
                    b.Property<int>("clsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clsID"));

                    b.Property<string>("clsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clsID");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("school_managment_system_backend.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("classroom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactperson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateofbirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("school_managment_system_backend.Models.Subject", b =>
                {
                    b.Property<int>("subId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subId"));

                    b.Property<string>("subName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("school_managment_system_backend.Models.Teacher", b =>
                {
                    b.Property<int>("teachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teachId"));

                    b.Property<string>("teachContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teachEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teachFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teachSecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("teachId");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
